using System.Collections.Generic;
using Artect.Generation.Emitters;

namespace Artect.Generation;

public static class EmitterRegistry
{
    public static IReadOnlyList<IEmitter> All() => new IEmitter[]
    {
        new ApiAuthEmitter(),
        new ApiDiEmitter(),
        new ArchitectureTestsEmitter(),
        new ApiFiltersEmitter(),
        new ApiProblemEmitter(),
        new ApiTestsEmitter(),
        new AppSettingsEmitter(),
        new ApplicationDiEmitter(),
        new ApplicationTestsEmitter(),
        new ArtectConfigEmitter(),
        new CommandRecordsEmitter(),
        new CsProjEmitter(),
        new DapperConnectionFactoryEmitter(),
        new DbContextEmitter(),
        new DtoMapperEmitter(),
        new DbFunctionsEmitter(),
        new DockerEmitter(),
        new DomainCommonEmitter(),
        new DomainTestsEmitter(),
        new DtoEmitter(),
        new EntityBehaviorEmitter(),
        new EntityConfigurationsEmitter(),
        new EntityEmitter(),
        new EntityDtoEmitter(),
        new EntityMappingsEmitter(),
        new EndpointRegistrationEmitter(),
        new EnumEmitter(),
        new HandlerEmitter(),
        new InfrastructureDiEmitter(),
        new InfrastructureInterceptorsEmitter(),
        new InfrastructureTestsEmitter(),
        new LaunchSettingsEmitter(),
        new MigrationsEmitter(),
        new MinimalApiEndpointEmitter(),
        new OutboxEmitter(),
        new OutboxDispatcherEmitter(),
        new PagedResponseEmitter(),
        new ProductionMiddlewareEmitter(),
        new ProgramCsEmitter(),
        new ReadServiceEmitter(),
        new ReadServiceInterfaceEmitter(),
        new RepoHygieneEmitter(),
        new RepositoryEmitter(),
        new RepositoryInterfaceEmitter(),
        new RequestEmitter(),
        new ResponseEmitter(),
        new SharedCommonEmitter(),
        new SlnEmitter(),
        new StoredProceduresEmitter(),
        new UnitOfWorkEmitter(),
        new UseCasesEmitter(),
        new ValidationErrorEmitter(),
        new ValidationResultEmitter(),
        new ApiValidatorsEmitter(),
        new ValidationResultExtensionsEmitter(),
    };
}
