using System;

namespace Artect.Generation;

public static class GeneratedByRegionWrapper
{
    public static EmittedFile Wrap(EmittedFile file, string label)
    {
        if (!file.RelativePath.EndsWith(".cs", StringComparison.Ordinal)) return file;
        if (IsHookFile(file.RelativePath)) return InsertHookHeader(file);
        return new EmittedFile(file.RelativePath, WrapTypeDeclaration(file.Contents, label));
    }

    static bool IsHookFile(string path) => path.EndsWith(".Extensions.cs", StringComparison.Ordinal);

    static EmittedFile InsertHookHeader(EmittedFile file)
    {
        var header = $"// User extension point. Safe to edit.{Environment.NewLine}";
        return new EmittedFile(file.RelativePath, header + file.Contents);
    }

    static string WrapTypeDeclaration(string source, string label)
    {
        var lines = source.Replace("\r\n", "\n").Split('\n');
        int typeStart = FindTypeDeclarationStart(lines);
        if (typeStart < 0) return source;
        var before = string.Join('\n', lines, 0, typeStart);
        var after = string.Join('\n', lines, typeStart, lines.Length - typeStart);
        var region = $"#region Generated by {label}\n{after}\n#endregion\n";
        return before + (before.EndsWith("\n") ? "" : "\n") + region;
    }

    static int FindTypeDeclarationStart(string[] lines)
    {
        for (int i = 0; i < lines.Length; i++)
        {
            var trimmed = lines[i].TrimStart();
            if (trimmed.StartsWith("public ") || trimmed.StartsWith("internal ") || trimmed.StartsWith("sealed ") ||
                trimmed.StartsWith("partial ") || trimmed.StartsWith("static ") || trimmed.StartsWith("abstract "))
            {
                if (trimmed.Contains("class ") || trimmed.Contains("record ") || trimmed.Contains("struct ") || trimmed.Contains("interface ") || trimmed.Contains("enum "))
                    return i;
            }
        }
        return -1;
    }
}
