using System;

namespace Artect.Generation;

public static class GeneratedByRegionWrapper
{
    public static EmittedFile Wrap(EmittedFile file, string label)
    {
        if (!file.RelativePath.EndsWith(".cs", StringComparison.Ordinal)) return file;
        if (IsHookFile(file.RelativePath)) return InsertHookHeader(file);
        return new EmittedFile(file.RelativePath, WrapTypeDeclaration(file.Contents, label));
    }

    static bool IsHookFile(string path) =>
        path.EndsWith(".Extensions.cs", StringComparison.Ordinal) ||
        path.EndsWith(".Behavior.cs", StringComparison.Ordinal);

    static EmittedFile InsertHookHeader(EmittedFile file)
    {
        var header = $"// User extension point. Safe to edit.{Environment.NewLine}";
        return new EmittedFile(file.RelativePath, header + file.Contents);
    }

    static string WrapTypeDeclaration(string source, string label)
    {
        var lines = source.Replace("\r\n", "\n").Split('\n');
        int typeStart = FindTypeDeclarationStart(lines);
        if (typeStart < 0) return source;
        var before = string.Join('\n', lines, 0, typeStart);
        var after = string.Join('\n', lines, typeStart, lines.Length - typeStart);
        var region = $"#region Generated by {label}\n{after}\n#endregion\n";

        // Always emit a blank line before the #region opener. Compute the separator
        // so `before + separator` ends in exactly "\n\n" (one line-terminator + one blank).
        string separator;
        if (before.EndsWith("\n\n", StringComparison.Ordinal))
            separator = string.Empty;
        else if (before.EndsWith("\n", StringComparison.Ordinal))
            separator = "\n";
        else
            separator = "\n\n";

        return before + separator + region;
    }

    static int FindTypeDeclarationStart(string[] lines)
    {
        for (int i = 0; i < lines.Length; i++)
        {
            var trimmed = lines[i].TrimStart();
            if (trimmed.StartsWith("public ") || trimmed.StartsWith("internal ") || trimmed.StartsWith("sealed ") ||
                trimmed.StartsWith("partial ") || trimmed.StartsWith("static ") || trimmed.StartsWith("abstract "))
            {
                if (trimmed.Contains("class ") || trimmed.Contains("record ") || trimmed.Contains("struct ") || trimmed.Contains("interface ") || trimmed.Contains("enum "))
                    return i;
            }
        }
        return -1;
    }
}
