using System.Collections.Generic;
using System.Linq;
using System.Text;
using Artect.Config;
using Artect.Core.Schema;
using Artect.Naming;
// Artect.Core.Schema.Index collides with System.Index — alias to the schema type.
using Index = Artect.Core.Schema.Index;

namespace Artect.Generation.Emitters;

/// <summary>
/// Emits a single <c>&lt;Project&gt;DbContext</c> class in
/// <c>&lt;Project&gt;.Infrastructure.Data</c>.
/// Per-entity configuration lives in IEntityTypeConfiguration classes generated by
/// <see cref="EntityConfigurationsEmitter"/>; this emitter only owns DbSet declarations,
/// sequence registration, view registration, and the
/// <c>ApplyConfigurationsFromAssembly</c> call.
/// Only runs when <c>cfg.DataAccess == EfCore</c>.
/// </summary>
public sealed class DbContextEmitter : IEmitter
{
    public IReadOnlyList<EmittedFile> Emit(EmitterContext ctx)
    {
        if (ctx.Config.DataAccess != DataAccessKind.EfCore)
            return System.Array.Empty<EmittedFile>();

        var project = ctx.Config.ProjectName;
        var content = Build(ctx, project);
        var path    = CleanLayout.DbContextPath(project, $"{project}DbContext");
        return new[] { new EmittedFile(path, content) };
    }

    static string Build(EmitterContext ctx, string project)
    {
        var model     = ctx.Model;
        var graph     = ctx.Graph;
        var dbCtx     = $"{project}DbContext";
        var entityNs  = $"{CleanLayout.DomainNamespace(project)}.Entities";
        var infraNs   = $"{CleanLayout.InfrastructureNamespace(project)}.Data";
        var appAbsNs  = CleanLayout.ApplicationAbstractionsNamespace(project);

        // V#12 conditional behaviors. We only inject ITenantContext + tenant-aware query
        // filters when at least one entity actually uses TenantId; ditto for soft delete.
        var anyTenant = model.Entities.Any(e => e.AnyColumnHasFlag(ColumnMetadata.TenantId));
        var anySoftDelete = model.Entities.Any(e => e.AnyColumnHasFlag(ColumnMetadata.SoftDeleteFlag));
        var emitOutbox = ctx.Config.EnableDomainEvents;
        var outboxNs = $"{CleanLayout.InfrastructureNamespace(project)}.Outbox";

        var collidedEntityNames = model.DbSets.EntityTypeNames.Values
            .GroupBy(v => v, System.StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToHashSet(System.StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine($"using {entityNs};");
        if (anyTenant)
            sb.AppendLine($"using {appAbsNs};");
        if (emitOutbox)
            sb.AppendLine($"using {outboxNs};");
        sb.AppendLine();
        sb.AppendLine($"namespace {infraNs};");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {dbCtx} : DbContext");
        sb.AppendLine("{");
        if (anyTenant)
        {
            // V#12: tenant-aware filter expression needs the current tenant id at model
            // build time. EF Core captures the parameterized expression once per
            // DbContext instance; switching tenants therefore requires a new DbContext
            // (which is the standard scoped-DbContext pattern in ASP.NET).
            sb.AppendLine("    private readonly ITenantContext _tenantContext;");
            sb.AppendLine();
            sb.AppendLine($"    public {dbCtx}(DbContextOptions<{dbCtx}> options, ITenantContext tenantContext) : base(options)");
            sb.AppendLine("    {");
            sb.AppendLine("        _tenantContext = tenantContext;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public {dbCtx}(DbContextOptions<{dbCtx}> options) : base(options) {{ }}");
        }
        sb.AppendLine();

        foreach (var entity in model.Entities)
        {
            // Mirror EntityEmitter's classification scope so every DbSet<T> has a matching
            // generated entity class. Owned entities don't normally have a DbSet (V#2 will
            // refine), but emitting one alongside the entity class keeps the build green
            // for the V#1 placeholder classification.
            if (entity.ShouldSkip(
                EntityClassification.AggregateRoot,
                EntityClassification.OwnedEntity,
                EntityClassification.ReadModel,
                EntityClassification.LookupData)) continue;
            var propertyName = entity.DbSetPropertyName;
            var typeName     = entity.EntityTypeName;
            var typeRef = collidedEntityNames.Contains(typeName)
                ? $"{entityNs}.{typeName}"
                : typeName;
            sb.AppendLine($"    public DbSet<{typeRef}> {propertyName} => Set<{typeRef}>();");
        }

        if (emitOutbox)
        {
            // V#13: outbox table is a transactional sibling of the aggregate writes —
            // exposing it as a DbSet keeps the dispatcher LINQ-queryable without dropping
            // to raw SQL.
            sb.AppendLine("    public DbSet<OutboxMessage> OutboxMessages => Set<OutboxMessage>();");
        }

        sb.AppendLine();
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");

        var orderedSequences = graph.Sequences
            .OrderBy(s => s.Schema, System.StringComparer.Ordinal)
            .ThenBy(s => s.Name, System.StringComparer.Ordinal);

        foreach (var seq in orderedSequences)
        {
            var clrType = SequenceClrType(seq.SqlType);
            sb.AppendLine($"        modelBuilder.HasSequence<{clrType}>(\"{seq.Name}\", \"{seq.Schema}\")");
            sb.AppendLine($"            .StartsAt({seq.StartValue})");
            sb.AppendLine($"            .IncrementsBy({seq.Increment});");
        }

        // Per-entity configuration is split out into IEntityTypeConfiguration classes.
        sb.AppendLine($"        modelBuilder.ApplyConfigurationsFromAssembly(typeof({dbCtx}).Assembly);");

        // V#12: emit query filters for SoftDeleteFlag and TenantId columns. Filters live
        // here (rather than in EntityConfigurations/) so the tenant filter can capture
        // _tenantContext from the DbContext instance — IEntityTypeConfiguration<T>
        // doesn't have a clean handle on instance state.
        if (anySoftDelete || anyTenant)
        {
            sb.AppendLine();
            foreach (var entity in model.Entities.OrderBy(e => e.EntityTypeName, System.StringComparer.Ordinal))
            {
                var softDeleteCol = entity.FirstColumnWithFlag(ColumnMetadata.SoftDeleteFlag);
                var tenantCol     = entity.FirstColumnWithFlag(ColumnMetadata.TenantId);
                if (softDeleteCol is null && tenantCol is null) continue;
                if (entity.ShouldSkip(
                    EntityClassification.AggregateRoot,
                    EntityClassification.OwnedEntity,
                    EntityClassification.ReadModel,
                    EntityClassification.LookupData)) continue;

                var entityRef = collidedEntityNames.Contains(entity.EntityTypeName)
                    ? $"{entityNs}.{entity.EntityTypeName}"
                    : entity.EntityTypeName;

                var predicates = new List<string>();
                if (softDeleteCol is not null)
                {
                    var prop = EntityNaming.PropertyName(softDeleteCol, ctx.NamingCorrections);
                    predicates.Add(softDeleteCol.ClrType switch
                    {
                        Artect.Core.Schema.ClrType.Boolean        => $"!e.{prop}",
                        Artect.Core.Schema.ClrType.DateTime       => $"e.{prop} == null",
                        Artect.Core.Schema.ClrType.DateTimeOffset => $"e.{prop} == null",
                        _ => $"!e.{prop}", // ConfigValidator rejects others; defensive default.
                    });
                }
                if (tenantCol is not null)
                {
                    var prop = EntityNaming.PropertyName(tenantCol, ctx.NamingCorrections);
                    predicates.Add($"e.{prop} == _tenantContext.CurrentTenantId");
                }
                var predicate = string.Join(" && ", predicates);
                sb.AppendLine($"        modelBuilder.Entity<{entityRef}>().HasQueryFilter(e => {predicate});");
            }
        }

        // View configurations stay inline — views don't fit the IEntityTypeConfiguration pattern
        // because they're keyless and the schema-derived view CLR type isn't enumerated by
        // EntityConfigurationsEmitter.
        foreach (var view in graph.Views)
        {
            var viewTypeName = CasingHelper.ToPascalCase(Pluralizer.Singularize(view.Name), ctx.NamingCorrections);
            sb.AppendLine($"        modelBuilder.Entity<{viewTypeName}>(b =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            b.ToView(\"{view.Name}\", \"{view.Schema}\");");
            sb.AppendLine("            b.HasNoKey();");
            foreach (var c in view.Columns)
            {
                var prop = EntityNaming.PropertyName(c, ctx.NamingCorrections);
                sb.AppendLine($"            b.Property(e => e.{prop}).HasColumnName(\"{c.Name}\");");
            }
            sb.AppendLine("        });");
            sb.AppendLine();
        }

        sb.AppendLine("        base.OnModelCreating(modelBuilder);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string SequenceClrType(string sqlType) => sqlType.ToLowerInvariant() switch
    {
        "bigint"   => "long",
        "int"      => "int",
        "smallint" => "short",
        "tinyint"  => "byte",
        "decimal" or "numeric" => "decimal",
        _ => "long",
    };
}
